name: LegacyLock
softdepend:
  - MythicMobs
main: me.sumbiz.legacylock.LegacyLock
version: 1.0.0
api-version: "1.21"
commands:
  legacylock:
    usage: "/legacylock <reload|edit normal|edit ominous>"
    permission: legacylock.admin
permissions:
  legacylock.admin:
    default: op
